import { Test, TestingModule } from '@nestjs/testing';
import { CryptoService } from './crypto.service.js';
import { scryptSync } from 'node:crypto';

describe('CryptoService', () => {
  let service: CryptoService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [CryptoService],
    }).compile();

    service = module.get<CryptoService>(CryptoService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('hash and verify', () => {
    it('should hash a password and verify it', () => {
      const password = 'Password123!';
      const hash = service.hash(password);
      expect(hash).toContain('scrypt$');
      expect(service.verify(password, hash)).toBe(true);
    });

    it('should fail verification for incorrect password', () => {
      const password = 'Password123!';
      const hash = service.hash(password);
      expect(service.verify('WrongPassword', hash)).toBe(false);
    });

    it('should be compatible with hashes generated by old logic', () => {
      const password = 'test-legacy';
      const salt = 'abcd';
      const hash = scryptSync(password, salt, 64).toString('hex');
      const fullHash = `scrypt$${salt}$${hash}`;

      expect(service.verify(password, fullHash)).toBe(true);
    });
  });

  describe('generateToken', () => {
    it('should generate a base64url token of correct length', () => {
      const token = service.generateToken(24);
      expect(token).toBeDefined();
      expect(typeof token).toBe('string');
      // base64url for 24 bytes is 32 chars
      expect(token).toHaveLength(32);
    });

    it('should generate tokens of different lengths', () => {
      const token16 = service.generateToken(16);
      // base64url for 16 bytes is approx 22 chars
      expect(token16.length).toBeLessThan(service.generateToken(24).length);
    });
  });
});
